### ISSUE TITLE
CheapETH mining guide in one command line

### ISSUE THREAD

**Issue by Sanix-Darker** [geohot/cheapeth-website#51]
I created a simple tool b4sh.co, to compress a lot of commands into one, i think this can be a good thing for the mining guide on cheapETH !

To install CheapETH
https://b4sh.co/cheapETH_install_80ed6 : 
![carbon (13)](https://user-images.githubusercontent.com/22576758/109556990-cbc25500-7ad7-11eb-8880-d356de1c6ee4.png)

instead of multiple commands : 
![Screenshot from 2021-03-01 21-50-34](https://user-images.githubusercontent.com/22576758/109557292-31aedc80-7ad8-11eb-86db-a6e623677382.png)

**Comment by geohot** [comment]
The guide sadly doesn't really work anymore, as the CPU miner is useless now. It's only good for running a node.
